### PR TITLE
update register btn of register.html and update thankyou.html

### PR DESCRIPTION
**Pull request by atul120212**
Screenshot 2023-10-24 230021
Screenshot 2023-10-24 225957

### CODE REVIEW

**Comment by atul120212** [comment]
issue #30

**Review by IshaanAdarsh — APPROVED** [review]
Great work. Looks good to me.
@nown1ne check it out an merge it

**Review by nown1ne — CHANGES_REQUESTED** [review]
Great work @atul120212 
The thank you page doesnt redirect to the home page please look into it 
also the position of the register button was better earlier

**Comment by atul120212** [comment]
I will update it  @nown1ne

**Review by nown1ne — APPROVED** [review]

**Comment by nown1ne** [comment]
Incredible work @atul120212 
Consider starring the repo for better reach
Looking forward to more awesome contributions from you 🚀

**Pull request merged**
