### PR TITLE
Added scrolling animation

### PR DESCRIPTION
**Pull request by Madanraj0519**
Feature: #91 

Just added a Scroll animation to the page. When the user scroll the main page it seem some fade animation while scrolling

https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/125730836/6a8f5eb3-f6ae-473b-8611-13113a224436

### CODE REVIEW

**Review by nown1ne — CHANGES_REQUESTED** [review]
Incredible work @Madanraj0519 
but I think the fade animation's duration can be reduced as the actual content is hindered by the animation

**Comment by Madanraj0519** [comment]
Thanks @nown1ne, I will reduce the duration and  again give you PR

**Comment by Madanraj0519** [comment]
https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/125730836/63e020e0-4671-49ce-bdd0-5e39c8438bf3

How about these changes? If it satisfies you I will give the PR

**Comment by nown1ne** [comment]
Alright looking good commit the changes and we can merge this

**Review by nown1ne — APPROVED** [review]
Incredible work @Madanraj0519  !!
Looking forward to more awesome contributions from you 🚀
Consider starring the repo for better reach

**Pull request merged**
