### PR TITLE
Fix Broken Links, Update Navigation, and Add Smooth Scrolling Animation

### LINKED ISSUE #4: Identify and Fix Broken Links
**Description**
Ensure a seamless user experience by identifying and fixing any broken links on the website. Review the site's links and update or remove any links that no longer work.

**Difficulty**
Easy

### PR DESCRIPTION
**Pull request by yashwanthvarma18**
Closes #4 by @nown1ne 

This pull request addresses several issues and introduces improvements to the website. Here's a breakdown of the changes made:

Details:

Broken Links Fixed:

Corrected broken links that were leading to non-existent pages. All links have been verified and updated for seamless navigation.
Update "Achievements" to "Events":

Replaced the "Achievements" link in the navigation bar with "Events" to better reflect the content and purpose of the page.
Add Smooth Scrolling Animation:

Implemented a smooth scrolling animation when clicking on the "Know Our Team" link in the navigation bar. Now, users will experience a visually pleasing transition when navigating to the team details section.
These changes enhance the overall user experience and ensure that the website functions as intended. Please review the updates, and if everything looks good, consider merging this PR.

Thank you for your attention to these improvements, and I look forward to your feedback.

### CODE REVIEW

**Comment by nown1ne** [comment]
Please make sure that you mention the issue your pr closes.

**Review by nown1ne — APPROVED** [review]
Awesome Work @yashwanthvarma18 !!
Looking forward to more contributions from you 🚀 
Consider starring the repo for better reach

**Comment by yashwanthvarma18** [comment]
thanks for thw oppertunity will this be counted for hactoberfest

**Comment by yashwanthvarma18** [comment]
thanks for the oppertunity @nown1ne will this be counted for hactoberfest

**Comment by nown1ne** [comment]
yes it will be counted for hacktoberfest

**Pull request merged**
