### PR TITLE
Fix issue 6

### PR DESCRIPTION
**Pull request by sarafurd**
#6 
### All Submissions:

- [x] Have you followed the guidelines stated in [README.md](https://github.com/NITRR-Open-Source-Community/NOSC-Website#how-to-contribute) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/NITRR-Open-Source-Community/NOSC-Website/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by IshaanAdarsh — COMMENTED** [review]
@nown1ne, look through it.
I think this works. just see if anything major has been changed

**Review by nown1ne — APPROVED** [review]
Incredible work @sarafurd 
Looking forward to more awesome contributions from you 🚀
Consider starring the repo for better reach

**Comment by nown1ne** [comment]
Dear @sarafurd  please ensure that you edit the code in inline and not replace the existing code as that makes it extremely hard for us to review the code.
and always make sure that you have the latest changes in your local copy of the repo by running the pull command before submitting a pr

waiting for your new pr based on the updated codebase

**Comment by sarafurd** [comment]
I did the git pull before making the branch

image

**Comment by sarafurd** [comment]
I made a new pull request

**Pull request merged**
