### PR TITLE
fix: achievements -> events

### PR DESCRIPTION
**Pull request by Snowfall22**
## Events Page URL Fix:
closes issue #53

### Bug fix

- Changed the url of events page from /achievements to /events.

events

### CODE REVIEW

**Comment by Snowfall22** [comment]
@nown1ne Please have a look and lmk.
thanks for assigning

**Review by nown1ne — APPROVED** [review]
Incredible work @Snowfall22  
Looking forward to more awesome contributions from you 🚀 
Consider starring the repo for better reach

**Comment by nown1ne** [comment]
Please resolve conflicts so that we can merge this asap 🚀

**Comment by Snowfall22** [comment]
Done

**Pull request merged**
