### PR TITLE
added link to privacy policy page

### LINKED ISSUE #23: Link the privacy policy page
**Description**
Link the privacy policy page to the 'link' link of the navbar and footer

**Difficulty**
easy

**Expected behavior**
The 'link' text should be changed to privacy policy and should direct to the privacy policy page

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by khushpreetsinghb**
closes #23 by @nown1ne 
### All Submissions:

- [x]  Have you followed the guidelines stated in [README.md](https://github.com/NITRR-Open-Source-Community/NOSC-Website#how-to-contribute) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/NITRR-Open-Source-Community/NOSC-Website/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.
   Updated/Added the Link to the Privacy Policy Page

    b. Describe your changes.
   Updated the Privacy Policy Link in the Navbar and Footer

### CODE REVIEW

**Comment by nown1ne** [comment]
please make sure that you mention the issue you pr closes

**Review by nown1ne — COMMENTED** [review]
Great work @khushpreetsinghb !!
Due to the recently merged prs there are a few conflicts please resolve them so that we can merge this ASAP 🚀

**Comment by khushpreetsinghb** [comment]
#### Resolved conflicts

Merged branch main and resolved conflicts in the footer section.

Fixes: #36

**Review by nown1ne — APPROVED** [review]
all clear

**Comment by khushpreetsinghb** [comment]
Thank you

**Pull request merged**
