### PR TITLE
Fixed Register Button

### PR DESCRIPTION
**Pull request by princyballabh**
#106 
### All Submissions:

- [ ] Have you followed the guidelines stated in [README.md](https://github.com/NITRR-Open-Source-Community/NOSC-Website#how-to-contribute) file?
- [ ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/NITRR-Open-Source-Community/NOSC-Website/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by nown1ne — APPROVED** [review]
Incredible work @princyballabh 
Looking forward to more awesome contributions from you 🚀
Consider starring the repo for better reach

**Comment by nown1ne** [comment]
Resolve conflicts so we can merge this asap

**Comment by princyballabh** [comment]
Resolved the conflicts!

**Review by IshaanAdarsh — COMMENTED** [review]
great work

**Pull request merged**
