### PR TITLE
Validation

### PR DESCRIPTION
**Pull request by Omar-Nabil**
I addressed an issue in the registration form validation to ensure that user input is appropriately validated before submission. The following changes have been implemented:

Name Validation:
Added validation for the name field to ensure it is not left blank.
Display a validation message prompting the user to enter a name if the field is empty.

Email Validation:
Implemented regular expression validation for the email field to ensure a valid email format.
Displays a validation message if an invalid email format is detected.

Phone Number Validation:
Set a minimum length requirement of 8 digits for the phone number field.
Displays a validation message if the entered phone number is less than 8 digits.

Password Validation:
Set a minimum length requirement of 8 characters for the password field.
Displays a validation message if the password length is below the specified limit.

Confirm Password Validation:
Implemented a check to ensure that the confirmation password matches the original password.
Displays a validation message if the confirmation password does not match.

Submit Button Validation:
Created a function to validate all form fields when the user attempts to register.
Calls individual validation functions for each field.

These changes aim to enhance the user experience by providing clear feedback on registration form errors, helping users correct their input before submission.

### CODE REVIEW

**Comment by Omar-Nabil** [comment]
https://github.com/NITRR-Open-Source-Community/NOSC-Website/pull/138

**Comment by Omar-Nabil** [comment]
i edited it can you check it  ? https://github.com/NITRR-Open-Source-Community/NOSC-Website/issues/132

**Comment by nown1ne** [comment]
Please resolve conflicts so that we can merge this ASAP 🚀

**Comment by Omar-Nabil** [comment]
@nown1ne which conflicts do you mean ? can you explain more ?

**Comment by nown1ne** [comment]
image
image


Conflicts occur when changes in your branch conflict with changes in the target branch. When mulitple people contribute to a project the code keeps changing. So by the time you submit your pr the original code might have changed therefore you have adjust you changes according to the current state of the repo

To resolve conflicts:

Pull the latest changes from the main branch into your branch.
Address any merge conflicts in your files.
Commit the resolved changes.
Push the updated branch.
Once conflicts are resolved, we can review and merge your pull request.

**Comment by Omar-Nabil** [comment]
https://github.com/NITRR-Open-Source-Community/NOSC-Website/pull/148 

i hope you can merge it now

**Pull request closed without merging**
