### PR TITLE
Fixed Webpage clipping issue

### LINKED ISSUE #42: Webpage padding issue causes horizontal overflow
**Description**
The webpage has irregular padding conflicts which makes a horizontal scrollbar appear and the body leaks out to the right side of the viewport.

**Difficulty**
Beginner-friendly

**To Reproduce**
1. Go to website
2. See error

**Expected behavior**
The content shouldn't overflow horizontally from the viewport and the user should not be able to scroll to the right.

**Screenshots**
Screenshot 2023-10-01 123216

**Desktop:**
 - OS: Windows 10
 - Browser: Mozilla Firefox
 - Version: 118.0.1 (64-bit)

### PR DESCRIPTION
**Pull request by ashmitsinghk**
### All Submissions:

- [x] Have you followed the guidelines stated in [README.md](https://github.com/NITRR-Open-Source-Community/NOSC-Website#how-to-contribute) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/NITRR-Open-Source-Community/NOSC-Website/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.
Fixed Webpage clipping issue

    b. Describe your changes.
The width property of #nav was conflicting with the predefined styles of Bootstrap which caused the webpage to clip out horizontally on some browsers. I have fixed the CSS file so the issue no longer persists.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
Closes #42

### CODE REVIEW

**Comment by ashmitsinghk** [comment]
#Screenshot:
Here is the screenshot after fixing the issue #42 :

image

**Review by IshaanAdarsh — APPROVED** [review]
Incredible work @ashmitsinghk !!
Looking forward to more awesome contributions from you 🚀
Consider starring the repo for better reach

**Comment by IshaanAdarsh** [comment]
@nown1ne just check for any issues. I think its good enough.

**Comment by nown1ne** [comment]
Looks good to me too
Great work @ashmitsinghk

**Pull request merged**
