### PR TITLE
HTML and CSS file updated

### PR DESCRIPTION
**Pull request by harishghasolia07**
Solved Issue No #9

### CODE REVIEW

**Comment by bhalerao-2002** [comment]
Hi @nown1ne and @harishghasolia07,
You added a great Contributor section. 👌 But you have changed various main body changes.
lead to problems like:-
nav logo:-
image
footer:-
image

**Comment by harishghasolia07** [comment]
> Hi @nown1ne and @harishghasolia07, You(@harishghasolia07 ) added a great Contributor section. 👌 But you have changed various main body changes. lead to problems like:- nav logo:- image footer:- image

When I run this website on my system it seems ok
NavBar-
Screenshot from 2023-10-01 15-24-10
Footer-
Screenshot from 2023-10-01 15-24-52

**Comment by nown1ne** [comment]
Youll have to make sure that your local code is always up to date with the code in the repo as everytime a pr is merged the code changes in the repo but you local copy remains unchanged
therefore before making a pr make sure that you pull the latest version of the repo otherwise youll have to resolve conflicts

**Comment by harishghasolia07** [comment]
Actually I'm new in open source contribution so I have no idea how to resolve conflicts. So please can you tell me what I should do right now? 

> Youll have to make sure that your local code is always up to date with the code in the repo as everytime a pr is merged the code changes in the repo but you local copy remains unchanged therefore before making a pr make sure that you pull the latest version of the repo otherwise youll have to resolve conflicts

**Comment by harishghasolia07** [comment]
What I need to remove the repo from my account and again fork and create a pull request or what?

**Comment by harishghasolia07** [comment]
Now I have the latest repo so can I re-create a pull request? @nown1ne

**Comment by nown1ne** [comment]
yes that would be best

**Pull request closed without merging**
